### ISSUE TITLE
Cannot open spread sheet file after downloading by G-drive add-on

### ISSUE THREAD

**Issue by poletaka** [ni/labview-gdrive#16]
I made VI using G-drive file downloading add-on function and spread sheet opening function, which are connected by using error flow sequentially. CSV file is successfully downloaded, but CSV file could not be opened sequentially.
 So CSV file might be continue to open by G-drive add-on, that spread sheet opening function might be able not to access the CSV file.
 File downloading function from G-drive does not have .net reference output terminal. So, I made  .net reference output terminal on File downloading function from G-drive. After that I connected .net reference close function after the downloading function, but cannot be improved.
Once the VI forced to be stopped after downloading, CSV file could be accessed by Labview or Microsoft EXCEL.
please advise me to the issue.
I use a Labview 2018.

**Comment by rdesrosier** [comment]
It sounds like a file reference is still open. Have you checked to see if there is a method in the .NET library to close the file after downloading, prior to closing the .NET reference?

**Comment by poletaka** [comment]
Thanks for the advice.
We solved it by connecting the closed invoke node later to the invoked node of the file stream. Thank you very much.
